/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroomIndexRouteImport } from './routes/groom.index'
import { Route as GroomReportRouteImport } from './routes/groom.report'
import { Route as GroomStableRouteImport } from './routes/groom.stable'
import { Route as GroomTasksRouteImport } from './routes/groom.tasks'
import { Route as TrainerIndexRouteImport } from './routes/trainer.index'
import { Route as TrainerAlertsRouteImport } from './routes/trainer.alerts'
import { Route as TrainerHorsesRouteImport } from './routes/trainer.horses'
import { Route as TrainerTrainingRouteImport } from './routes/trainer.training'
import { Route as VetIndexRouteImport } from './routes/vet.index'
import { Route as VetAlertsRouteImport } from './routes/vet.alerts'
import { Route as VetHorsesRouteImport } from './routes/vet.horses'
import { Route as VetMedicalRouteImport } from './routes/vet.medical'
import { Route as HorseRoleIdRouteImport } from './routes/horse.$role.$id'
import { Route as LiveRoleHorseIdRouteImport } from './routes/live.$role.$horseId'
import { Route as TrainerPlanIdRouteImport } from './routes/trainer.plan.$id'
import { Route as VetExamIdRouteImport } from './routes/vet.exam.$id'
import { Route as VetInjuryIdRouteImport } from './routes/vet.injury.$id'
import { Route as VetLockIdRouteImport } from './routes/vet.lock.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroomIndexRoute = GroomIndexRouteImport.update({
  id: '/groom/',
  path: '/groom/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroomReportRoute = GroomReportRouteImport.update({
  id: '/groom/report',
  path: '/groom/report',
  getParentRoute: () => rootRouteImport,
} as any)
const GroomStableRoute = GroomStableRouteImport.update({
  id: '/groom/stable',
  path: '/groom/stable',
  getParentRoute: () => rootRouteImport,
} as any)
const GroomTasksRoute = GroomTasksRouteImport.update({
  id: '/groom/tasks',
  path: '/groom/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerIndexRoute = TrainerIndexRouteImport.update({
  id: '/trainer/',
  path: '/trainer/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerAlertsRoute = TrainerAlertsRouteImport.update({
  id: '/trainer/alerts',
  path: '/trainer/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerHorsesRoute = TrainerHorsesRouteImport.update({
  id: '/trainer/horses',
  path: '/trainer/horses',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerTrainingRoute = TrainerTrainingRouteImport.update({
  id: '/trainer/training',
  path: '/trainer/training',
  getParentRoute: () => rootRouteImport,
} as any)
const VetIndexRoute = VetIndexRouteImport.update({
  id: '/vet/',
  path: '/vet/',
  getParentRoute: () => rootRouteImport,
} as any)
const VetAlertsRoute = VetAlertsRouteImport.update({
  id: '/vet/alerts',
  path: '/vet/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const VetHorsesRoute = VetHorsesRouteImport.update({
  id: '/vet/horses',
  path: '/vet/horses',
  getParentRoute: () => rootRouteImport,
} as any)
const VetMedicalRoute = VetMedicalRouteImport.update({
  id: '/vet/medical',
  path: '/vet/medical',
  getParentRoute: () => rootRouteImport,
} as any)
const HorseRoleIdRoute = HorseRoleIdRouteImport.update({
  id: '/horse/$role/$id',
  path: '/horse/$role/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoleHorseIdRoute = LiveRoleHorseIdRouteImport.update({
  id: '/live/$role/$horseId',
  path: '/live/$role/$horseId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerPlanIdRoute = TrainerPlanIdRouteImport.update({
  id: '/trainer/plan/$id',
  path: '/trainer/plan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VetExamIdRoute = VetExamIdRouteImport.update({
  id: '/vet/exam/$id',
  path: '/vet/exam/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VetInjuryIdRoute = VetInjuryIdRouteImport.update({
  id: '/vet/injury/$id',
  path: '/vet/injury/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VetLockIdRoute = VetLockIdRouteImport.update({
  id: '/vet/lock/$id',
  path: '/vet/lock/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/groom/report': typeof GroomReportRoute
  '/groom/stable': typeof GroomStableRoute
  '/groom/tasks': typeof GroomTasksRoute
  '/trainer/alerts': typeof TrainerAlertsRoute
  '/trainer/horses': typeof TrainerHorsesRoute
  '/trainer/training': typeof TrainerTrainingRoute
  '/vet/alerts': typeof VetAlertsRoute
  '/vet/horses': typeof VetHorsesRoute
  '/vet/medical': typeof VetMedicalRoute
  '/groom/': typeof GroomIndexRoute
  '/trainer/': typeof TrainerIndexRoute
  '/vet/': typeof VetIndexRoute
  '/horse/$role/$id': typeof HorseRoleIdRoute
  '/live/$role/$horseId': typeof LiveRoleHorseIdRoute
  '/trainer/plan/$id': typeof TrainerPlanIdRoute
  '/vet/exam/$id': typeof VetExamIdRoute
  '/vet/injury/$id': typeof VetInjuryIdRoute
  '/vet/lock/$id': typeof VetLockIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/groom/report': typeof GroomReportRoute
  '/groom/stable': typeof GroomStableRoute
  '/groom/tasks': typeof GroomTasksRoute
  '/trainer/alerts': typeof TrainerAlertsRoute
  '/trainer/horses': typeof TrainerHorsesRoute
  '/trainer/training': typeof TrainerTrainingRoute
  '/vet/alerts': typeof VetAlertsRoute
  '/vet/horses': typeof VetHorsesRoute
  '/vet/medical': typeof VetMedicalRoute
  '/groom': typeof GroomIndexRoute
  '/trainer': typeof TrainerIndexRoute
  '/vet': typeof VetIndexRoute
  '/horse/$role/$id': typeof HorseRoleIdRoute
  '/live/$role/$horseId': typeof LiveRoleHorseIdRoute
  '/trainer/plan/$id': typeof TrainerPlanIdRoute
  '/vet/exam/$id': typeof VetExamIdRoute
  '/vet/injury/$id': typeof VetInjuryIdRoute
  '/vet/lock/$id': typeof VetLockIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/groom/report': typeof GroomReportRoute
  '/groom/stable': typeof GroomStableRoute
  '/groom/tasks': typeof GroomTasksRoute
  '/trainer/alerts': typeof TrainerAlertsRoute
  '/trainer/horses': typeof TrainerHorsesRoute
  '/trainer/training': typeof TrainerTrainingRoute
  '/vet/alerts': typeof VetAlertsRoute
  '/vet/horses': typeof VetHorsesRoute
  '/vet/medical': typeof VetMedicalRoute
  '/groom/': typeof GroomIndexRoute
  '/trainer/': typeof TrainerIndexRoute
  '/vet/': typeof VetIndexRoute
  '/horse/$role/$id': typeof HorseRoleIdRoute
  '/live/$role/$horseId': typeof LiveRoleHorseIdRoute
  '/trainer/plan/$id': typeof TrainerPlanIdRoute
  '/vet/exam/$id': typeof VetExamIdRoute
  '/vet/injury/$id': typeof VetInjuryIdRoute
  '/vet/lock/$id': typeof VetLockIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/groom/report'
    | '/groom/stable'
    | '/groom/tasks'
    | '/trainer/alerts'
    | '/trainer/horses'
    | '/trainer/training'
    | '/vet/alerts'
    | '/vet/horses'
    | '/vet/medical'
    | '/groom/'
    | '/trainer/'
    | '/vet/'
    | '/horse/$role/$id'
    | '/live/$role/$horseId'
    | '/trainer/plan/$id'
    | '/vet/exam/$id'
    | '/vet/injury/$id'
    | '/vet/lock/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/groom/report'
    | '/groom/stable'
    | '/groom/tasks'
    | '/trainer/alerts'
    | '/trainer/horses'
    | '/trainer/training'
    | '/vet/alerts'
    | '/vet/horses'
    | '/vet/medical'
    | '/groom'
    | '/trainer'
    | '/vet'
    | '/horse/$role/$id'
    | '/live/$role/$horseId'
    | '/trainer/plan/$id'
    | '/vet/exam/$id'
    | '/vet/injury/$id'
    | '/vet/lock/$id'
  id:
    | '__root__'
    | '/'
    | '/groom/report'
    | '/groom/stable'
    | '/groom/tasks'
    | '/trainer/alerts'
    | '/trainer/horses'
    | '/trainer/training'
    | '/vet/alerts'
    | '/vet/horses'
    | '/vet/medical'
    | '/groom/'
    | '/trainer/'
    | '/vet/'
    | '/horse/$role/$id'
    | '/live/$role/$horseId'
    | '/trainer/plan/$id'
    | '/vet/exam/$id'
    | '/vet/injury/$id'
    | '/vet/lock/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroomReportRoute: typeof GroomReportRoute
  GroomStableRoute: typeof GroomStableRoute
  GroomTasksRoute: typeof GroomTasksRoute
  TrainerAlertsRoute: typeof TrainerAlertsRoute
  TrainerHorsesRoute: typeof TrainerHorsesRoute
  TrainerTrainingRoute: typeof TrainerTrainingRoute
  VetAlertsRoute: typeof VetAlertsRoute
  VetHorsesRoute: typeof VetHorsesRoute
  VetMedicalRoute: typeof VetMedicalRoute
  GroomIndexRoute: typeof GroomIndexRoute
  TrainerIndexRoute: typeof TrainerIndexRoute
  VetIndexRoute: typeof VetIndexRoute
  HorseRoleIdRoute: typeof HorseRoleIdRoute
  LiveRoleHorseIdRoute: typeof LiveRoleHorseIdRoute
  TrainerPlanIdRoute: typeof TrainerPlanIdRoute
  VetExamIdRoute: typeof VetExamIdRoute
  VetInjuryIdRoute: typeof VetInjuryIdRoute
  VetLockIdRoute: typeof VetLockIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groom/': {
      id: '/groom/'
      path: '/groom'
      fullPath: '/groom/'
      preLoaderRoute: typeof GroomIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groom/report': {
      id: '/groom/report'
      path: '/groom/report'
      fullPath: '/groom/report'
      preLoaderRoute: typeof GroomReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groom/stable': {
      id: '/groom/stable'
      path: '/groom/stable'
      fullPath: '/groom/stable'
      preLoaderRoute: typeof GroomStableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groom/tasks': {
      id: '/groom/tasks'
      path: '/groom/tasks'
      fullPath: '/groom/tasks'
      preLoaderRoute: typeof GroomTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/': {
      id: '/trainer/'
      path: '/trainer'
      fullPath: '/trainer/'
      preLoaderRoute: typeof TrainerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/alerts': {
      id: '/trainer/alerts'
      path: '/trainer/alerts'
      fullPath: '/trainer/alerts'
      preLoaderRoute: typeof TrainerAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/horses': {
      id: '/trainer/horses'
      path: '/trainer/horses'
      fullPath: '/trainer/horses'
      preLoaderRoute: typeof TrainerHorsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/training': {
      id: '/trainer/training'
      path: '/trainer/training'
      fullPath: '/trainer/training'
      preLoaderRoute: typeof TrainerTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/': {
      id: '/vet/'
      path: '/vet'
      fullPath: '/vet/'
      preLoaderRoute: typeof VetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/alerts': {
      id: '/vet/alerts'
      path: '/vet/alerts'
      fullPath: '/vet/alerts'
      preLoaderRoute: typeof VetAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/horses': {
      id: '/vet/horses'
      path: '/vet/horses'
      fullPath: '/vet/horses'
      preLoaderRoute: typeof VetHorsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/medical': {
      id: '/vet/medical'
      path: '/vet/medical'
      fullPath: '/vet/medical'
      preLoaderRoute: typeof VetMedicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horse/$role/$id': {
      id: '/horse/$role/$id'
      path: '/horse/$role/$id'
      fullPath: '/horse/$role/$id'
      preLoaderRoute: typeof HorseRoleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$role/$horseId': {
      id: '/live/$role/$horseId'
      path: '/live/$role/$horseId'
      fullPath: '/live/$role/$horseId'
      preLoaderRoute: typeof LiveRoleHorseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/plan/$id': {
      id: '/trainer/plan/$id'
      path: '/trainer/plan/$id'
      fullPath: '/trainer/plan/$id'
      preLoaderRoute: typeof TrainerPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/exam/$id': {
      id: '/vet/exam/$id'
      path: '/vet/exam/$id'
      fullPath: '/vet/exam/$id'
      preLoaderRoute: typeof VetExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/injury/$id': {
      id: '/vet/injury/$id'
      path: '/vet/injury/$id'
      fullPath: '/vet/injury/$id'
      preLoaderRoute: typeof VetInjuryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/lock/$id': {
      id: '/vet/lock/$id'
      path: '/vet/lock/$id'
      fullPath: '/vet/lock/$id'
      preLoaderRoute: typeof VetLockIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroomReportRoute: GroomReportRoute,
  GroomStableRoute: GroomStableRoute,
  GroomTasksRoute: GroomTasksRoute,
  TrainerAlertsRoute: TrainerAlertsRoute,
  TrainerHorsesRoute: TrainerHorsesRoute,
  TrainerTrainingRoute: TrainerTrainingRoute,
  VetAlertsRoute: VetAlertsRoute,
  VetHorsesRoute: VetHorsesRoute,
  VetMedicalRoute: VetMedicalRoute,
  GroomIndexRoute: GroomIndexRoute,
  TrainerIndexRoute: TrainerIndexRoute,
  VetIndexRoute: VetIndexRoute,
  HorseRoleIdRoute: HorseRoleIdRoute,
  LiveRoleHorseIdRoute: LiveRoleHorseIdRoute,
  TrainerPlanIdRoute: TrainerPlanIdRoute,
  VetExamIdRoute: VetExamIdRoute,
  VetInjuryIdRoute: VetInjuryIdRoute,
  VetLockIdRoute: VetLockIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
